# Generated by Django 5.2.7 on 2025-12-10 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('item_name', models.CharField(max_length=200)),
                ('pickup_date', models.DateTimeField()),
                ('food_type', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('cooked', 'Cooked Food'), ('others', 'Others')], max_length=50)),
                ('quantity', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=255, null=True)),
                ('consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='available', max_length=20)),
                ('is_deleted_by_donor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_contact', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.donation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('expiring_soon', 'Expiring Soon'), ('very_close_to_expiry', 'Very Close to Expiry'), ('expired', 'Expired')], default='fresh', max_length=20)),
                ('notified_6', models.BooleanField(default=False)),
                ('notified_2', models.BooleanField(default=False)),
                ('notified_expired', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
